// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/v1/mesh.proto

package meshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_v1_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_v1_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PingResponse) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *PingResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_api_proto_v1_mesh_proto protoreflect.FileDescriptor

const file_api_proto_v1_mesh_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/mesh.proto\x12\fapi.proto.v1\"C\n" +
	"\vPingRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"f\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\x03R\n" +
	"receivedAt\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName2L\n" +
	"\vMeshService\x12=\n" +
	"\x04Ping\x12\x19.api.proto.v1.PingRequest\x1a\x1a.api.proto.v1.PingResponseB?Z=github.com/Chalupa-Tech/go-telemetry-mesh/api/proto/v1;meshv1b\x06proto3"

var (
	file_api_proto_v1_mesh_proto_rawDescOnce sync.Once
	file_api_proto_v1_mesh_proto_rawDescData []byte
)

func file_api_proto_v1_mesh_proto_rawDescGZIP() []byte {
	file_api_proto_v1_mesh_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_mesh_proto_rawDesc), len(file_api_proto_v1_mesh_proto_rawDesc)))
	})
	return file_api_proto_v1_mesh_proto_rawDescData
}

var file_api_proto_v1_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_mesh_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: api.proto.v1.PingRequest
	(*PingResponse)(nil), // 1: api.proto.v1.PingResponse
}
var file_api_proto_v1_mesh_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.MeshService.Ping:input_type -> api.proto.v1.PingRequest
	1, // 1: api.proto.v1.MeshService.Ping:output_type -> api.proto.v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_mesh_proto_init() }
func file_api_proto_v1_mesh_proto_init() {
	if File_api_proto_v1_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_mesh_proto_rawDesc), len(file_api_proto_v1_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_mesh_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_mesh_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_mesh_proto_msgTypes,
	}.Build()
	File_api_proto_v1_mesh_proto = out.File
	file_api_proto_v1_mesh_proto_goTypes = nil
	file_api_proto_v1_mesh_proto_depIdxs = nil
}
