---
name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  release-deploy:
    uses: Chalupa-Tech/chalupa-infra/.github/workflows/release-reusable.yml@main
    with:
      image_name: go-telemetry-mesh
      values_path: k8s/apps/telemetry-mesh/values.yaml
    secrets: inherit
